# ***Python for ML/DL***
---
<center>
<img src="https://ehackz.com/wp-content/uploads/2018/02/Python.jpg" 
height = "50%" width = "70%">

In [2]:
import numpy as np
import torch
import tensorflow as tf

## **Tensor**

### **Torch**
---
- **Initialize Pytorch's tensor**

In [5]:
tensor_list = torch.tensor([1, 2, 4, 5]) #Convert a Python's list for Pytorch's tensor
#print(tensor_list)
tensor_numpy = torch.tensor(np.random.randn(3,2)) #Convert for Pytorch'a tensor
#print(tensor)
tensor_numpy_1 = torch.from_numpy(np.random.randn(3,2)) 
##Convert Numpy array for Pytorch'a tensor
#print(tensor_numpy_1) 
tensor_float32 = torch.empty(size = (3, 4)) #Initialize  Pytorch's tensor with dtype float32.
#print(tensor)
tensor_zeros = torch.zeros_like(tensor_float32) 
#Initialize Pytorch's tensor with same shape tensor float32
#print(tensor_zeros) 
tensor_ones = torch.ones((3,2)) #Initialize Pytorch's tensor of ones
#print(tensor_ones)
tensor_eyes = torch.eye(5,5) 
#Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.
#print(tensor_eyes)
tensor_arange = torch.arange(start=1, end=20, step=3) 
#Pytorch's tensor with [x+3, x+6, x+9,...] sequence

**Convert Pytorch's tensor to ...**

In [46]:
tensor_convert = torch.tensor(np.random.randn(3,3))
print(tensor_convert.int(),'\n') #convert values Pytorch tensor to int32
print(tensor_convert.bool(),'\n') #convert values pytorch tensor to boolen
print(tensor_convert.float(), '\n') #convert values pytorch tensor to float32
print(tensor_convert.numpy(), '\n') #convrt pytorch tensor to numpy array

tensor([[-1,  0,  0],
        [-1,  0,  0],
        [ 0,  0,  1]], dtype=torch.int32) 

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]]) 

tensor([[-1.1628,  0.3329,  0.4296],
        [-1.3063, -0.6097, -0.6267],
        [-0.6229, -0.7377,  1.7460]]) 

[[-1.16278542  0.33292708  0.4296377 ]
 [-1.30625093 -0.60968602 -0.62668454]
 [-0.6228853  -0.73767189  1.74602179]] 



### **shape**

In [43]:
tensor_list.shape
tensor_float32.shape
tensor_zeros.shape

### **Index**

In [42]:
tensor_float32[0] #Access to tensor with 2D for all the first rown
tensor_float32[:] #Access all the tensor
tensor_float32[1:, :] #Acces to sice second rown until last rown and all column  

### **Compare tensors**
---
- torch tensor

- tensorflow tensor

In [5]:
img = tf.constant(np.random.randn(4, 4, 3))*0.01 # shape  [height, width, color_channels]

img  = torch.rand(3, 4, 4) # shape (channels, rown, column)

In [4]:
img_more_example = torch.rand(5, 3, 8, 8) # shape (batch_size, channels, rown, column)
img_more_example = tf.Variable(np.random.randn(5, 8, 8, 3)) 
#shape (batch_size, rown, column, channels)

**[Operation with Tensor](https://medium.com/analytics-vidhya/pytorch-part1-9a63a063de31)**

In [163]:
x =  torch.tensor([[1, 2, 4, 5]]) 
#Create a Pytorch's tensor 
y =  torch.tensor([[1, 2, 4, 5]])
#Create a Pytorch's tensor

z = x + y  #Addition
#z = torch.add(x, y) #proof 
#print(z)

z = x - y  #Substraction
#z = torch.sub(x, y) #proof
#print(z)

z = x * y #Wise Multy
#z = torch.mm(x.T, y) # Matrix Multiplication 
#z = torch.dot(x, y) # Matrix dot product
#print(z)



z = torch.true_divide(x, y) #Division
#print(z)

z = x ** 2  #Pow
#z = torch.matrix_power(x, 2) #proof
#print(z) 

## **Broadcasting**

In [49]:
example_1 = torch.rand((2, 4))
example_2 = torch.rand((1, 4))

print(example_1 + example_2, '\n')
print(torch.true_divide(example_2, example_1), '\n')

tensor([[1.6511, 1.3060, 0.9616, 0.9937],
        [1.6532, 1.0537, 1.2476, 1.7126]]) 

tensor([[1.0239, 0.9900, 0.8337, 2.6836],
        [1.0212, 1.6083, 0.5394, 0.7322]]) 



### **[unsqueeze](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html)**

Returns a new tensor with a dimension of size one inserted at the specified position.

A dim value within the range [-input.dim() - 1, input.dim() + 1) can be used. Negative dim will correspond to unsqueeze() applied at dim = dim + input.dim() + 1.

In [99]:
x = torch.tensor([[1, 2, 3, 4], [2, 3, 6, 3]])  
#Expected to be in range of [-3, 2] , tensor 2D shape [2, 4]

torch.unsqueeze(x, -3).unsqueeze(3).shape  #shape ??  

torch.Size([1, 2, 4, 1])

In [109]:
tensor_1 = torch.randn(2, 3, 5, 5)
tensor_2 = torch.randn(3, 1, 1)
(tensor_1 + tensor_2).shape

torch.Size([2, 3, 5, 5])

In [188]:
torch_eye = torch.tensor([[1, 0, 0], 
                          [0, 0, 1], 
                          [0, 1, 0]])
torch.max(torch_eye, dim=0)

torch.return_types.max(values=tensor([1, 1, 1]), indices=tensor([0, 2, 1]))

## **Moving tensors to GPU**

In [12]:
tensor_gpu = torch.tensor(np.random.randn(3, 4, 4), device='cuda')

In [13]:
tensor_gpu = img.to(device= 'cuda')

In [14]:
device = 'cuda' if torch.cuda.is_available else 'cpu'
tensor_gpu.to(device=device)

tensor([[[0.0633, 0.7552, 0.9489, 0.5855],
         [0.0539, 0.7949, 0.1653, 0.8080],
         [0.1182, 0.2571, 0.5503, 0.5415],
         [0.8357, 0.8037, 0.1432, 0.2735]],

        [[0.9916, 0.9885, 0.7092, 0.0180],
         [0.1020, 0.7994, 0.4515, 0.9751],
         [0.6581, 0.5432, 0.6755, 0.4545],
         [0.4521, 0.8461, 0.7149, 0.5417]],

        [[0.2283, 0.7322, 0.6143, 0.8275],
         [0.8980, 0.0502, 0.9908, 0.9815],
         [0.3917, 0.8269, 0.0238, 0.0482],
         [0.7104, 0.7135, 0.3543, 0.6880]]], device='cuda:0')

In [15]:
tensor_gpu = tensor_gpu + 4

In [16]:
tensor_gpu = tensor_gpu.to(device='cpu') + 2
tensor_gpu

tensor([[[6.0633, 6.7552, 6.9489, 6.5855],
         [6.0539, 6.7949, 6.1653, 6.8080],
         [6.1182, 6.2571, 6.5503, 6.5415],
         [6.8357, 6.8037, 6.1432, 6.2735]],

        [[6.9916, 6.9885, 6.7092, 6.0180],
         [6.1020, 6.7994, 6.4515, 6.9751],
         [6.6581, 6.5432, 6.6755, 6.4545],
         [6.4521, 6.8461, 6.7149, 6.5417]],

        [[6.2283, 6.7322, 6.6143, 6.8275],
         [6.8980, 6.0502, 6.9908, 6.9815],
         [6.3917, 6.8269, 6.0238, 6.0482],
         [6.7104, 6.7135, 6.3543, 6.6880]]])

## **Real-world data representation using tensors**

## **Working with images**

In [129]:
import imageio 

img = imageio.imread('../src/image.png')

In [130]:
img.shape #Height width Channel

(243, 702, 4)

## **Don't forget** 

Pytorch tensor when working with an image, the dimension has to be C x H x W

In [131]:
img = torch.from_numpy(img)

In [132]:
img.shape #Height  width Channel

torch.Size([243, 702, 4])

In [133]:
img_1 = img.permute(2, 0, 1)
img_1.shape

torch.Size([4, 243, 702])

In [134]:
img.shape

torch.Size([243, 702, 4])

## **Parser Argument**
---
If you want to see the code of parser.py, base_option.py you could check [here](https://github.com/alexliqu09/Python_for_ML_and_DL/tree/main/src)


In [207]:
!python ../src/parser.py 3

Your argument is: 3 and the result is: 1.004969823313689


In [54]:
!python ../src/function.py tanh  3

0.9950547536867306


In [25]:
!python ../src/base_option.py  --lr_decay 7 --epoch 50 --batch_size 4 --model "AlexNet"

============Training Model==========
           model:AlexNet
           batch_size: 4
           epoch: 50
           input_nc: 3
           lr_decay: 7
           gpu_is: 0
------------------------------------


## **Decorators**

## **Simple decorator**

In [2]:
def my_decorator(function):
    def print_Init_format():
        print("=============Initialize parameters===========\n")
        function()
        print("===========================================\n")
    return print_Init_format

def initializer_weight():
    W1 = tf.constant(np.random.randn(2, 3), tf.float16)*0.01
    b1 = tf.constant(np.zeros((2, 1)), tf.float16)
    W2 = tf.constant(np.random.randn(2, 3), tf.float16)*0.01
    b2 = tf.constant(np.zeros((2, 1)), tf.float16)
    print("W1: {},\n\nW2: {},\n\nb1: {},\n\nb2: {} ".format(W1, W2, b1, b2))

decorator = my_decorator(initializer_weight)

decorator()

=============Initialize parameters===========

W1: [[-0.00808   0.004425  0.02357 ]
 [-0.001951 -0.004627  0.01457 ]],

W2: [[-0.0004516 -0.008736   0.01617  ]
 [-0.010185  -0.005676  -0.01481  ]],

b1: [[0.]
 [0.]],

b2: [[0.]
 [0.]] 



### **[Pie-decorator](https://www.python.org/dev/peps/pep-0318/#background)**

Python allows you to use decorators in a simpler way with the @ symbol, sometimes called the “pie” syntax. 


In [ ]:
def my_decorator(function):
    def print_Init_format():
        print("=============Initialize parameters===========\n")
        function()
        print("===========================================\n")
    return print_Init_format

@my_decorator
def initializer_weight():
    W1 = tf.constant(np.random.randn(2, 3), tf.float16)*0.01
    b1 = tf.constant(np.zeros((2, 1)), tf.float16)
    W2 = tf.constant(np.random.randn(2, 3), tf.float16)*0.01
    b2 = tf.constant(np.zeros((2, 1)), tf.float16)

    print("W1: {},\n\nW2: {},\n\nb1: {},\n\nb2: {} ".format(W1, W2, b1, b2))

initializer_weight()

## **Decorating Functions With Arguments**


In [3]:
def initilizer(func):
    def wrapper(*args):
        function = func(*args)
        print(f"Original sigmoid:\n\n{function},\n\nSigmoid > 0.5\n\n{function[function > 0.5]}")
    return wrapper

@initilizer
def sigmoid(x):
    return 1/(1 + np.exp(-x))


sigmoid(torch.tensor(np.random.randn(3,2)))

Original sigmoid:

[[0.4740459  0.28621845]
 [0.66564275 0.63275348]
 [0.08450159 0.71326616]],

Sigmoid > 0.5

[0.66564275 0.63275348 0.71326616]


### **Numba**

In [13]:
from numba import jit 
from time import time

In [87]:
matrix_random = np.random.rand(10,10)

In [88]:
def multiplicacion_matricial(X, Y):
    matrix_mult = np.zeros_like(matrix_random)
    for rown in range(len(X)):
        for  column in range(len(Y[0])):
            for aux in range(len(Y)):
                matrix_mult[rown, column] += X[rown, aux]*Y[aux, column]
    return matrix_mult

In [89]:
start = time()
multiplicacion_matricial(matrix_random, matrix_random)

finish = time()
print(f"time: {finish - start} ")

time: 0.002145051956176758 


In [83]:
@jit
def multiplicacion_matricil_jit(X, Y):
    matrix_mult = np.zeros_like(matrix_random)
    for rown in range(len(X)):
        for  column in range(len(Y[0])):
            for aux in range(len(Y)):
                matrix_mult[rown, column] += X[rown, aux]*Y[aux, column]
    return matrix_mult

In [90]:
start = time()
multiplicacion_matricil_jit(matrix_random, matrix_random)
finish = time()
print(f"time: {finish - start} ")

time: 0.00012993812561035156 


### **tf.function**