# ***Python for ML/DL***
---
<center>
<img src="https://ehackz.com/wp-content/uploads/2018/02/Python.jpg" 
height = "50%" width = "70%">

In [1]:
import numpy as np
import torch
import tensorflow as tf

## **Tensor**

### **Torch**

In [6]:
x = torch.tensor([1, 2, 4, 5]) #Convert a Python's list for Pytorch's tensor
#print(X)
x = torch.tensor(np.random.randn(3,2)) #Convert Numpy array for Pytorch'a tensor
#print(x)
  

tensor([[-0.0486, -1.9073],
        [-0.5751, -0.3748],
        [ 1.4850, -2.4018]], dtype=torch.float64)


## **Parser Argument**

## **Decorators**

## **Simple decorator**

In [2]:
def my_decorator(function):
    def print_Init_format():
        print("=============Initialize parameters===========\n")
        function()
        print("===========================================\n")
    return print_Init_format

def initializer_weight():
    W1 = tf.constant(np.random.randn(2, 3), tf.float16)*0.01
    b1 = tf.constant(np.zeros((2, 1)), tf.float16)
    W2 = tf.constant(np.random.randn(2, 3), tf.float16)*0.01
    b2 = tf.constant(np.zeros((2, 1)), tf.float16)
    print("W1: {},\n\nW2: {},\n\nb1: {},\n\nb2: {} ".format(W1, W2, b1, b2))

decorator = my_decorator(initializer_weight)

decorator()

=============Initialize parameters===========

W1: [[-0.00808   0.004425  0.02357 ]
 [-0.001951 -0.004627  0.01457 ]],

W2: [[-0.0004516 -0.008736   0.01617  ]
 [-0.010185  -0.005676  -0.01481  ]],

b1: [[0.]
 [0.]],

b2: [[0.]
 [0.]] 



### **[Pie-decorator](https://www.python.org/dev/peps/pep-0318/#background)**

Python allows you to use decorators in a simpler way with the @ symbol, sometimes called the “pie” syntax. 


In [ ]:
def my_decorator(function):
    def print_Init_format():
        print("=============Initialize parameters===========\n")
        function()
        print("===========================================\n")
    return print_Init_format

@my_decorator
def initializer_weight():
    W1 = tf.constant(np.random.randn(2, 3), tf.float16)*0.01
    b1 = tf.constant(np.zeros((2, 1)), tf.float16)
    W2 = tf.constant(np.random.randn(2, 3), tf.float16)*0.01
    b2 = tf.constant(np.zeros((2, 1)), tf.float16)

    print("W1: {},\n\nW2: {},\n\nb1: {},\n\nb2: {} ".format(W1, W2, b1, b2))

initializer_weight()

## **Decorating Functions With Arguments**


In [3]:
def initilizer(func):
    def wrapper(*args):
        function = func(*args)
        print(f"Original sigmoid:\n\n{function},\n\nSigmoid > 0.5\n\n{function[function > 0.5]}")
    return wrapper

@initilizer
def sigmoid(x):
    return 1/(1 + np.exp(-x))


sigmoid(torch.tensor(np.random.randn(3,2)))

Original sigmoid:

[[0.4740459  0.28621845]
 [0.66564275 0.63275348]
 [0.08450159 0.71326616]],

Sigmoid > 0.5

[0.66564275 0.63275348 0.71326616]
