# ***Python for ML/DL***
---
<center>
<img src="https://ehackz.com/wp-content/uploads/2018/02/Python.jpg" height = "40%" width = "60%">

## **Object Oriented Programming**

OOP is a paradigm of program where the component is divided into objects that have data and behaviors and communicate with each other.
<center>
<img src="https://wideinfo.org/wp-content/uploads/2018/08/mahirkoding_oop-1200x762_c.jpg" height="60%" width="65%">

## **Class**

The class is a template that contains general characteristics of the objects of that class.

<center>
<img src="https://media.geeksforgeeks.org/wp-content/cdn-uploads/20190501121513/inheritance.png" height="60%" width="50%">

## **Objects**

**Objects** are generally real-life bodies that contain data and behaviors, and these objects are created by **instantiating** a class.

-  Atributtes: Attributes are the individual characteristics that differentiate one object from another and determine its appearance, state, or other qualities.

-  Methods: On objects it is possible to perform actions (operations, calculations)


<center>
<img src="https://miro.medium.com/max/810/1*xiYI_rl-_pX_27BAjxBL3g.png"  height="40%" width="50%">

## Note:
- [self](https://www.geeksforgeeks.org/self-in-python-class/):  By using the “self” keyword we can access the attributes and methods of the class in python. It binds the attributes with the given arguments. self is parameter in function and user can use another parameter name in place of it.

**Example 1**

define a Class

In [61]:
class Car():
    marca = "Auidi"
    largo = 250
    ancho = 150
    placa = "AB3X"
    Estado = True
    def cahge_estado(self, estado):
        self.Estado = estado
        return self.Estado 
    def resume(self):
        print(f"marca: {auto.marca}, ancho: {auto.ancho},  Estado: {auto.Estado}")
auto = Car()
auto_2 = Car()

### Access to atributtes and methods.

In [62]:
auto.cahge_estado(False)

auto.resume()


marca: Auidi, ancho: 150,  Estado: False


### Compare

In [101]:
auto.cahge_estado(True)

auto_2.resume()

marca: Auidi, ancho: 150,  Estado: True


## **Constructor**

**[Init](https://www.tutorialspoint.com/What-is-difference-between-self-and-init-methods-in-python-Class#:~:text=__init__%20method,the%20attributes%20of%20the%20class.)**: This method is called when an object is created from a class and it allows the class to initialize the attributes of the class.

**Example 2**

Use the  __init__ method

In [200]:
class Laptop():
    def __init__(self, name, processor, gpu, ram):
        self.name = name
        self.processor = processor
        self.gpu = gpu
        self.ram = ram 
    def resume(self):
            return f"The laptop {self.name}, the processor is {self.processor}, the GPU: {self.gpu} and the ram is {self.ram}."

lap1 = Laptop("ASUS","Intel","GEFORCE_RTX_3070","8GB")
lap2 = Laptop("Lenovo","Intel","GEFORCE_RTX_3070","8GB")

In [201]:
print(f"{lap1.resume()}\n{lap2.resume()}")

The laptop ASUS, the processor is Intel, the GPU: GEFORCE_RTX_3070 and the ram is 8GB.
The laptop Lenovo, the processor is Intel, the GPU: GEFORCE_RTX_3070 and the ram is 8GB.


 ## **Encapsulate**
 you can restrict access to methods and variables. This can prevent the data from being modified by accident and is known as encapsulation.

In [7]:
class Student():
    def __init__(self, name, surname, id, carrear):
        self.__name = name
        self.__surname = surname
        self.__id = id
        self.__carrear = carrear
    def resume(self):
        return f"the name: {self.__name}, the surname: {self.__surname}, the id: {self.__id} and the carrear: {self.__carrear}"
student1 = Student("Alexander", "Lique", "20192196K", "computer science")

In [8]:
student1.resume()
student1.__name = "R"
student1.resume()

'the name: Alexander, the surname: Lique, the id: 20192196K and the carrear: computer science'

In [170]:
save = lap1.__str__()

## **Special methods**
---

Python has
Multiple special predefined methods in your classes and you can easily recognize as they have two underscores _ _method_ _ ()

### **del**

The __del__() method is a known as a destructor method in Python. It is called when all references to the object have been deleted i.e when an object is garbage collected.

### **str**

This method is applied when the object is called to display, in other words this is a representative string of the class.


In [166]:
class Laptop():
    def __init__(self, name="Asus", processor="Intel", gpu="GEFORCE_RTX_3070", ram="8GB"):
        self.name = name
        self.processor = processor
        self.gpu = gpu
        self.ram = ram 
    def __str__(self):
            return f"The laptop {self.name}, the processor is {self.processor}, the GPU: {self.gpu} and the ram is {self.ram}."
    def __del__(self):
        print(f"Delete the objetc:  {self.__str__()}")

In [167]:
if __name__ == "__main__":
    lap3 = Laptop()
    lap3 = Laptop("Asus","Ryzen","GEFORCE_RTX_3070","16GB")

Delete the objetc:  The laptop Asus, the processor is Intel, the GPU: GEFORCE_RTX_3070 and the ram is 8GB.


**Compare lap1 and lap3**

In [168]:
print(lap3)

The laptop Asus, the processor is Ryzen, the GPU: GEFORCE_RTX_3070 and the ram is 16GB.


In [171]:
print(save)

### [len](https://docs.python.org/3/reference/datamodel.html#special-method-names):

Called to implement the built-in function len(). Should return the length of the object, an integer >= 0. Also, an object that doesn’t define a __bool__() method and whose __len__() method returns zero is considered to be false in a Boolean context.


### [getitem](https://www.geeksforgeeks.org/__getitem__-in-python/#:~:text=The%20__getitem__%20magic,Python's%20most%20underutilized%20magic%20methods.):
The __getitem__ method is usually used for list indexing, dictionary lookup, or accessing ranges of values. Considering how versatile it is, it’s probably one of Python’s most underutilized magic methods. 

### [repr](https://www.journaldev.com/22460/python-str-repr-functions):
function returns the object representation in string format.

In [212]:
class DataSet():
    def __init__(self, data):
        self.data = data
    def __len__(self):
        return len(self.data)
    def __getitem__(self, item):
        return type(self.data),item, self.data[item]
    def __repr__(self):
        return f"Data(data = {self.data})"
    def __setitem__(self, item, value):
        self.data[item] = value

data = ['image1.jpg','imag2.jpg','image3.jpg','img4.jpg']

d = DataSet(data)


In [213]:
len(d)

4

In [214]:
print(f"{d[0]}\n{d[::]}")

(<class 'list'>, 0, 'image1.jpg')
(<class 'list'>, slice(None, None, None), ['image1.jpg', 'imag2.jpg', 'image3.jpg', 'img4.jpg'])


In [215]:
d

Data(data = ['image1.jpg', 'imag2.jpg', 'image3.jpg', 'img4.jpg'])

In [216]:
d[0] = "image5.jpg"

d

Data(data = ['image5.jpg', 'imag2.jpg', 'image3.jpg', 'img4.jpg'])

## **Inheritance**

Inheritance is an object-oriented programming mechanism used to create new classes from existing classes. Attributes and behaviors are taken (inherited) from old classes and modified to model a new situation.

In [21]:
class Human():
    def __init__(self, name, 
                 years, sex, id):
        self.name = name
        self.years = years
        self.sex = sex
        self.id = id
    def __str__(self):
        return "I'm {}".format(self.name)
    def __repr__(self):
        return "My name is {}, I have {} years and my DNI is {}".format(self.name,self.years,self.id)
    def edad(self):
        return self.years
Human("Alexander", 20, "M", 75359501)

My name is Alexander, I have 20 years and my DNI is 75359501

In [22]:
class Empleado(Human):
    def __init__(self, name, years, 
        sex, id, specialization, salary):
        super(Empleado, self).__init__(name, years, sex, id)
        self.specialization = specialization
        self.salary = salary
    
    def __str__(self):
        return "I am {} and my specialization is {} ".format(
            self.name, self.specialization)


Empleado("Alexander", 20, "sex", 75359501, "Deep Learning Engineer", 2500)

My name is Alexander, I have 20 years and my DNI is 75359501

You can see Employee Inheritance the "age" methods

In [23]:
e1 = Empleado("Alexander", 20, "sex", 75359501, "Deep Learning Engineer", 2500)
e1.edad()

20

## **Polymorphism**

The OOP polymorphism technique means the ability to take on more than one shape. An operation can exhibit different behaviors in different instances

In [37]:
class Vehiculo():
    def __init__(self, velocidad):
        self.velocidad = velocidad

    def __str__(self):
        return ""


class Coche(Vehiculo):
    def __init__(self, velocidad):
        super(Coche, self).__init__(velocidad)
    
    def  __str__(self):
        return f"la velocidad es: {self.velocidad}"

class Camion(Vehiculo):
    def __init__(self, velocidad):
        super(Camion, self).__init__(velocidad)
    
    def  __str__(self):
        return f"la velocidad es: {self.velocidad}"    

def velocidad_vehiculo(Vehiculo):
    print(Vehiculo)

mi_vehiculo = Camion("30km/h")

mi_segundo_vehiculo = Coche("50km")

velocidad_vehiculo(mi_vehiculo)

la velocidad es: 30km/h


In [36]:
velocidad_vehiculo(mi_segundo_vehiculo)

la velocidad es: 50km


## **Funciones Lambda**

This is an anonymous function that in Python makes it easier to simplify fractions, however, if you use the conditional loop, it is not recommended to use this.
This function does not need to be declared as a conventional function because it just needs in a specific place.

**Example 1**

In [3]:
area_triangulo = lambda base, altura: (base*altura)/2
area_triangulo(3,5)

7.5

**Example 2**

In [20]:
impar = lambda num: num%2 != 0

True

**Example 3**

In [22]:
reverse  = lambda cadena: cadena[::-1]

[4, 2, 1]

**Example 4**

In [52]:
a = [1, 2, 4, 7]
s = list(map(lambda x : x ** 2, a))
print(s)

[1, 4, 16, 49]


**Example 5**

In [10]:
high_ord_func = lambda x, func: x + func(x)
high_ord_func(4, lambda x: x**2 * x+x)

72

**Save lambda function in a tuple**

<font color="red">
Sigmoid Activaction Function
<center>
<img src ="https://user-images.githubusercontent.com/12709287/30514320-5c0ba90e-9b4d-11e7-8ec4-1cd5c13db681.png" height="40%" width="40%"> 

In [40]:
import numpy as np

sigmoide  =  (lambda x: 1/(1+np.e**(-x)),
              lambda x: x*(1-x))
              
x = np.array([1,2,3,4])
sigmoide[0](x)

array([0.73105858, 0.88079708, 0.95257413, 0.98201379])

In [50]:
sigmoide[1](sigmoide[0](x))

array([0.19661193, 0.10499359, 0.04517666, 0.01766271])

The [map](https://www.w3schools.com/python/ref_func_map.asp) function executes a specified function for each item in an iterable. The item is sent to the function as a parameter.

In [55]:
valores = []
for e in x:
    valores=(list(map(lambda x: x(e),sigmoide)))
    print(valores)

[0.7310585786300049, 0]
[0.8807970779778823, -2]
[0.9525741268224331, -6]
[0.9820137900379085, -12]


In [48]:
message = lambda parameters : "My model have {} of parameters".format(parameters)
message(2000000)

'My model have 2000000 of parameters'

<font color="GREEN">
Relu Activaction Function
<center>
<img src ="https://miro.medium.com/max/754/1*3JUMOqugWKB2SDra6x6v0A.png" width="30%" height="30%">

In [8]:
relu = lambda x: np.maximum(0, x)

x = np.array([-1,2,-3,4])

relu(x)

array([0, 2, 0, 4])

<font color="Blue">
hyperbolic tangent
<center>
<img src="https://paperswithcode.com/media/methods/Screen_Shot_2020-05-27_at_4.23.22_PM_dcuMBJl.png" height="30%" width="40%">

In [44]:
tanh = lambda x: (np.e**(x)-np.e**(-x))/(np.e**(-x)+np.e**(x))

x = np.array([1,2,3,4])

tanh(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])