# ***Python for ML/DL***
---

<center>
<img src="https://ehackz.com/wp-content/uploads/2018/02/Python.jpg" height = "40%" width = "60%">

## **Introduction PEP8**

<center>
<img src="https://d2o2utebsixu4k.cloudfront.net/media/images/1a38e5b6-4815-4390-ad92-a52b825fba0b.jpg" height="70%" width="80%">

## What is PEP8?

[PEP 8](https://realpython.com/python-pep8/) (Python Enhancement Proposals), sometimes spelled PEP8 or PEP-8, is a document that provides guidelines and best practices on how to write Python code. It was written in 2001 by Guido van Rossum, Barry Warsaw, and Nick Coghlan. The primary focus of PEP 8 is to improve the readability and consistency of Python code.

### **Naming Conventions**

When you write Python code, you will avoid the inappropriate variables names . Choosing  names will save you time and you’ll be able to figure out, from the name, what a certain variable, function, or class represents.

### **Sytels**

**Function**: Use a word or words in lowercase and separate with underscore.

**Variable**: Use a lowercase single letter, word, or words. Separate words with underscores.

**Class**: Use upper in the first letter and don't separate the words with underscore.

**methods**: Use a lowercase word or words and separete with underscores.

**Constant**: Use an uppercase single letter, word, or words. Separate words with underscores

**Module**: Use lowercase word or words  with underscores.

**package**: Use lowercase and do not underscores.

**Variable**

In [7]:
full_name = "Juan Perez"
name, surname = full_name.split()

print(name, surname)

Juan Perez


## **Constant**

In [32]:
NAME_MOVIL_PHONE = [
    'Samsung',
    'Huaweii',
    'Nokia',
    'Claro'
]

NAME_MOVIL_PHONE

['Samsung', 'Huaweii', 'Nokia', 'Claro']

## **Function**

In [46]:
def random_choise():
    return None

**Class**

In [44]:
class MovilPhone():
    pass

### **Code Layout**

We also learn about indentation because it is very important to make your code more readable. Here you will learn how to handle the PEP8 recommended limit of 79 lines of characters.

Surround top-level functions and classes with two blank lines. 

In [54]:
class FirstClass():
    pass


class SecondClass():
    pass


def top_level_function():
    return None

Surround method definitions inside classes with a single blank line.

In [55]:
class MovilPhone():
    
    def __init__(self):
        return None

    def __str__(self):
        return None

Use blank lines sparingly inside functions to show clear steps.

In [52]:
import numpy as np


def normalization(name_array):

    mean = np.median(name_array)

    std = np.std(name_array)

    return (name_array - mean) / std

## **Maximum Line Length and Line Breaking**

PEP 8 suggests lines should be limited to 79 characters. This is because it allows you to have multiple files open next to one another, while also avoiding line wrapping.

In [56]:
def function(arg_1, arg_2, 
             arg_3, arg_4):
    return None

In [3]:
from torch import (nn, 
                   functional, 
                   cuda, 
                   onnx)

If line breaking needs to occur around binary operators, like + and *, it should occur before the operator. This rule stems from mathematics. Mathematicians agree that breaking before binary operators improves readability. 

In [69]:
lamda =  0.01

size = 50

weight_sum = 0.956 

regularization = (lamda 
            * weight_sum 
            / size)

## **Indentation Following Line Breaks**

When you’re using line continuations to keep lines to under 79 characters, it is useful to use indentation to improve readability. It allows the reader to distinguish between two lines of code and a single line of code that spans two lines.

In [ ]:
'''
while (flag==True or 
       count<200):
       print(count)
       -----
'''

In [64]:
flag = True

count = 0

while (flag and 
              count<5):
       count +=1

In [ ]:
flag = True

count = 0

while (flag==True and 
       count<5):
       #Here initialize the code
       count +=1

## **hanging indent**

In [70]:
def function(
        arg_1, arg_2,
        arg_3, arg_4):
    return None

In [72]:
var = function(
    1, 2,
    3, 4)


## **Closing Brace**

Line up the closing brace with the first non-whitespace character of the previous line:

In [73]:
prime = [
    2, 3, 5,
    7, 11, 13
    ]

Line up the closing brace with the first character of the line that starts the construct:

In [74]:
prime = [
    2, 3, 5,
    7, 11, 13
]

## **Block Comments**

They are useful when you have to write several lines of code to perform a single action, such as importing data from a file or updating a database entry. They are important as they help others understand the purpose and functionality of a given code block.

- Indent block comments to the same level as the code they describe.
- Start each line with a # followed by a single space.
- Separate paragraphs by a line containing a single #.



In [4]:
x = "John Smith"  # Student Name

empty_list = []  # Initialize empty list

x = 5  # This is an inline comment
x = x * 5  # Multiply x by 5

## **Documentation Strings**


Documentation strings, or docstrings, are strings enclosed in double (""") or single (''') quotation marks that appear on the first line of any function, class, method, or module. 

The most important rules applying to docstrings are the following:

Surround docstrings with three double quotes on either side, as in """This is a docstring""".

Write them for all public modules, functions, classes, and methods.

Put the """ that ends a multiline docstring on a line by itself

In [2]:
import torch.nn as nn
import torch.nn.functional as F


class Model(nn.Module):
    """This  is an subclass of super class nn.Module
    To create a subclass, you need implements the folowing two methods.
       --<__init__>: initialize the class; this module call the super(Model, self).__init__()
       --<forward>: produce intermediate results.
    """

    def __init__(self, opt):
        """Initialize the Model class
        Parameters:
            opt (option )-- pass a dictionary with the hypeparameters.
            when implements this class
            -- self.device (str): specify the device type.
            -- self.epoch (int): define the epoch.
            -- self.conv1 (torch.nn.modules.conv.Conv2d):  define the first conv2d
            -- self.conv2 (torch.nn.modules.conv.Conv2d): define the second conv2d
        """
        super(Model, self).__init__()
        self.device = opt["gpu_is"]
        self.epoch = opt["epoch"]
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)

    def forward(self, x):
        """Run forward pass"""
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))


## **Whitespace Around Binary Operators**

urround the following binary operators with a single space on either side:

- Assignment operators (=, +=, -=, and so forth)

- Comparisons (==, !=, >, <. >=, <=) and (is, is not, in, not in)

- Booleans (and, not, or)

In [77]:
def function(default_parameter = 5):
    pass

In [1]:
x = 1

y = x**4 + x**3 + x**2 + x + 0.1

z = (x+y)**2 * (y-x)**3

In [80]:
if x>5 and x%2==0:
    print('x is larger than 5 and divisible by 2!')

In [84]:
list_ = [1, 2, 4, 6, 7, 8]

list_[3:5]

# Treat the colon as the operator with lowest priority
list_[z+1 : z+2]

# In an extended slice, both colons must be
# surrounded by the same amount of whitespace
list_[3:4:5]
list_[z+1 : x+2 : x+3]

# The space is omitted if a slice parameter is omitted
list_[z+1 : z+2 :]

print("")

## **When to Avoid Adding Whitespace**

The most important place to avoid adding whitespace is at the end of a line. This is known as trailing whitespace. It is invisible and can produce errors that are difficult to trace.



In [ ]:
list_ = [1, 2, 4, 6, 7, 8]


In [ ]:
print(x, y)

- list_\[1]

- tuple_ = (1,)

In [88]:
var1 = 5
var2 = 6
some_long_var = 7

In [90]:
my_bool = True

if my_bool:
    print('6 is bigger than 5')

6 is bigger than 5


## **Online**

---

You so availble in the internet PEP8's corrector with for example:

- [PEP8 Online](http://pep8online.com/)  
- [PythonChecker](https://www.pythonchecker.com/)

## **Formatters**

- [Black](https://pypi.org/project/black/): **pip install black**

Black is the uncompromising Python code formatter. By using it, you agree to cede   control over minutiae of hand-formatting. In return, Black gives you speed,                  determinism, and freedom from pycodestyle nagging about formatting. You will save            time and mental energy for more important matters.

# **Numpy**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

<center>
<img src="https://techscript24.com/wp-content/uploads/2020/10/86498201-a8bd8680-bd39-11ea-9d08-66b610a8dc01.png" width="20% height="30%">


**Install Numpy**

pip install Numpy

**Import numpy**

In [2]:
import numpy as np

Convert a list in **Numpy** array

1.

In [23]:
numpy_array_example_1 = np.array([[1, 3, 4, 5]])

print("array:{}\n\n type: {}".format(numpy_array_example_1, type(numpy_array_example_1)))

array:[[1 3 4 5]]

 type: <type 'numpy.ndarray'>


In [24]:
print(numpy_array_example_1.shape)

(1, 4)


2.

In [26]:
numpy_array_example_2 = np.array([1, 3, 4, "hello"])

print("array:{}\n\n type: {}".format(numpy_array_example_2, type(numpy_array_example_2)))

array:['1' '3' '4' 'hello']

 type: <type 'numpy.ndarray'>


3. 

In [51]:
numpy_array_example_3 = np.array([[1, 3, 4, 3.4]])

print("array:{}\n\n type: {}".format(numpy_array_example_3, type(numpy_array_example_3)))

array:(1, 4)

 type: <type 'numpy.ndarray'>


---

In [55]:
numpy_array_example_1.dtype

dtype('int64')

In [64]:
numpy_array_example_1.shape

(1, 4)

In [62]:
numpy_array_example_1.ndim

2

In [60]:
numpy_array_example_1.size

4

In [69]:
numpy_array_example_1.itemsize

8

In [70]:
numpy_array_example_1.data

<read-write buffer for 0x7f8381cc8940, size 32, offset 0 at 0x7f8381c583b0>

## **Operation with Numpy**
---



### **Sum**

In [72]:
list_1 = [1, 2, 4, 5]  #Initialize a python's list

list_2 = [1, 5, 5, 4]  #Initialize a python's list 

In [81]:
list_array_1 = np.array([[1, 2, 4, 5]])  #Initialize a numpy array shape (1, 4)

list_array_2 = np.array([[1, 3, 5, 6]])  #Initialize a numpy array shape (1, 4)

**Compare**

In [79]:
print(list_1 + list_2)  #The list_2 is adding at the final of list_1

[1, 2, 4, 5, 1, 5, 5, 4]


In [78]:
print(list_array_1 + list_array_2)  #Don't forget arrays' sum with (1, 4) + (1, 4) -> (1, 4)

[[ 2  5  9 11]]


## Broadcasting
---

In [80]:
list_array_1 + 4  #Rember the shape for the list_array_1 ->(1,4) and the list is:[1, 2, 4, 5]

array([[5, 6, 8, 9]])

In [95]:
list_array_3 = [[1, 3, 4, 5], [1, 4, 5, 6]]  # Initialize a python's list  two sublist

list_array_3 = np.array(list_array_3) #Convert the list in Numpy's array with shape -> (2, 4)

list_array_2 + list_array_3  #Sum two Numpy arrays' with shape: (1, 4) + (2, 4) -> (2, 4)

array([[ 2,  6,  9, 11],
       [ 2,  7, 10, 12]])

In [106]:
list_array_4 =  [[1, 3, 4, 5]]  #Initialize a python's list (1, 4) 

list_array_4 = np.array(list_array_4) #Actualize the list_array_4 shape: (1, 4)

list_array_4 + list_array_2.T #shape (1, 4) + (4, 1) -> (4, 4)

array([[ 2,  4,  5,  6],
       [ 4,  6,  7,  8],
       [ 6,  8,  9, 10],
       [ 7,  9, 10, 11]])

Is it possible? What is the shape of this?

list_array_4 + list_array_3.T #shape (1, 4) + (4, 2) -> ?

**Division**

In [109]:
list_array_5 = np.random.randn(2, 6) #Initialize numpy's array 

list_array_6 = np.random.randn(1,6) #Initialize numpy's array

In [123]:
list_array_5 / 3 #Divide with three

array([[ 0.08880278, -0.15692396,  0.50227734,  0.75372394, -0.10482422,
        -0.09868096],
       [-0.0394082 ,  0.03715227, -0.12289026,  0.00133819,  0.38420478,
        -0.16264112]])

In [113]:
list_array_6 / list_array_5 # Divide (1, 6) / (2, 6) -> (2, 6)

array([[ -2.23436106,  -5.16067012,  -0.20325389,  -0.05027103,
          1.08418275,   1.68437749],
       [  5.03492905,  21.79766721,   0.83073972, -28.31463808,
         -0.29580217,   1.02198009]])

In [117]:
list_array_4 / list_array_6.T #Divede (1, 4) / (6, 1) -> (6, 4)

array([[ -1.6799595 ,  -5.0398785 ,  -6.71983801,  -8.39979751],
       [  0.41160759,   1.23482277,   1.64643036,   2.05803795],
       [ -3.26509852,  -9.79529557, -13.06039409, -16.32549262],
       [ -8.79728437, -26.39185312, -35.18913749, -43.98642186],
       [ -2.93301735,  -8.79905204, -11.73206939, -14.66508673],
       [ -2.00542277,  -6.01626831,  -8.02169108, -10.02711386]])

Is it possible?  What is the shape of this?

- list_array_4 / list_array_6 #shape (1, 4) / (1, 6) -> ?

- shape (2, 5) / (3, 1) -> ?

## **Vectorization**

In [142]:
import math

math_sigmoid = lambda x: 1 / (1 + math.exp(-x))

numpy_sigmoid = lambda x : 1 / (1 + np.exp(-x)) 

In [132]:
vector_example_1 = np.random.rand(1, 6)

vector_example_1

array([[0.66228848, 0.14566119, 0.32989347, 0.02052255, 0.36830701,
        0.15360747]])

In [176]:
auxiliar_array = np.empty(vector_example_1.shape[1])

for ix in range(vector_example_1.shape[1]):
    auxiliar_array[ix] = math_sigmoid(vector_example_1[0][ix])

auxiliar_array

array([0.65977428, 0.53635105, 0.58173346, 0.50513046, 0.59104983,
       0.53832654])

In [143]:
numpy_sigmoid(vector_example_1)

array([[0.65977428, 0.53635105, 0.58173346, 0.50513046, 0.59104983,
        0.53832654]])